### ISSUE TITLE
Generalise "Gates" capabilities for OAReport

### ISSUE THREAD

**Issue by markmacgillivray** [oaworks/paradigm#55] opened 2022-01-20 09:15 UTC

**Comment by markmacgillivray** [comment] 2022-02-08 07:31
@JosephMcArthur this is just my general placeholder issue on paradigm about the things needing done, and for this one about generalising what we do for Gates I have had some more thoughts. Just bringing this up for possible discussion at our meeting tomorrow if there's time, so assigning it to myself for now too as I'll continue to work on this until we get to the point of being able to review permissions/deposit and get those pushed to live.

**Comment by markmacgillivray** [comment] 2022-02-17 10:13
Nothing else done here this week since we last talked about it, will hopefully do some next week.

**Comment by JosephMcArthur** [comment] 2022-03-01 10:57
Unassigning you here until we complete embed

**Comment by JosephMcArthur** [comment] 2022-03-14 11:38
Closing as a duplicate of https://github.com/oaworks/Gates/issues/24

**Closed by JosephMcArthur** 2022-03-14 11:38 UTC
